name: Maven Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'ro.gs1.quarkus-config-etcd'
          package-type: maven
          ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
          min-versions-to-keep: 2

      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'ro.gs1.quarkus-config-etcd-parent'
          package-type: maven
          ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
          min-versions-to-keep: 2

      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'ro.gs1.quarkus-config-etcd-deployment'
          package-type: maven
          ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
          min-versions-to-keep: 2

      - name: Build with Maven
        run: mvn -B package --file pom.xml -q -Pgithub
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -Dmaven.test.skip=true -q -Pgithub
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}