# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml # location for the settings.xml file

    - uses: actions/delete-package-versions@v2
      with: 
        package-name: 'ro.gs1.quarkus-config-etcd'
        ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
        min-versions-to-keep: 0
        
    - uses: actions/delete-package-versions@v2
      with: 
        package-name: 'ro.gs1.quarkus-config-etcd-parent'
        ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
        min-versions-to-keep: 0
        
    - uses: actions/delete-package-versions@v2
      with: 
        package-name: 'ro.gs1.quarkus-config-etcd-deployment'
        ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
        min-versions-to-keep: 0

    - name: Build with Maven
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B package --file pom.xml -Dmaven.test.skip=true -q
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -Dmaven.test.skip=true -q
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
